tags/version1.0/CbaGob.Alumnos.Web/Controllers/EstablecimientosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CbaGob.Alumnos.Servicio.Servicios;
using CbaGob.Alumnos.Servicio.ServiciosInterface;
using CbaGob.Alumnos.Servicio.Vistas;
using CbaGob.Alumnos.Servicio.VistasInterface;
using JLY.Hotel.Web.Controllers;

namespace CbaGob.Alumnos.Web.Controllers
{
    public class EstablecimientosController : BaseController
    {
        private IEstablecimientoServicio establecimientoservicio;
        private IInstitucionServicio institucionservicio;

        //
        // GET: /Establecimientos/


        public EstablecimientosController(IEstablecimientoServicio establecimientoservicio, IInstitucionServicio institucionservicio)
        {
            this.establecimientoservicio = establecimientoservicio;
            this.institucionservicio = institucionservicio;
        }

        public ActionResult Index()
        {
            IEstablecimientosVista model = new EstablecimientosVista();

            model = establecimientoservicio.GetAllEstablecimiento();

            return View(model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        public ActionResult Agregar(int Id_institucion)
        {

            IEstablecimientoVista model = new EstablecimientoVista();

            model.Id_Institucion = Id_institucion;

            model.NombreInstitucion = institucionservicio.GetUnaVista(Id_institucion).Nombre_Institucion;

            return View(model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        public ActionResult Modificar(int id_establecimiento)
        {
            IEstablecimientoVista model;

            model = establecimientoservicio.GetEstablecimiento(id_establecimiento);

            return View(model);
        }
        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        public ActionResult Eliminar(int id_establecimiento)
        {
            IEstablecimientoVista model;

            model = establecimientoservicio.GetEstablecimiento(id_establecimiento);

            return View(model);
        }

        public ActionResult Consultar(int id_establecimiento)
        {
            IEstablecimientoVista model;

            model = establecimientoservicio.GetEstablecimiento(id_establecimiento);

            return View(model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        [HttpPost]
        public ActionResult Agregar_Establecimiento(EstablecimientoVista model)
        {

            model.Id_Institucion = model.Id_Institucion;
            bool mRet = establecimientoservicio.AgregarEstablecimiento(model);

            if (mRet == true)
            {
                IEstablecimientosVista establecimientosvista = new EstablecimientosVista();

                establecimientosvista = establecimientoservicio.GetAllEstablecimiento();

                return RedirectToAction("Ver", "Instituciones", new { INST_ID = model.Id_Institucion });
            }
            else
            {
                base.AddError(establecimientoservicio.GetErrors());
                model.Id_Institucion = model.Id_Institucion;
                model.NombreInstitucion = institucionservicio.GetUnaVista(model.Id_Institucion).Nombre_Institucion;
                return View("Agregar", model);
            }
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        [HttpPost]
        public ActionResult Eliminar_Establecimiento(EstablecimientoVista model)
        {


            bool mRet = establecimientoservicio.EliminarEstablecimiento(model.Id_Establecimiento, model.Nro_Resolucion);

            IEstablecimientosVista establecimientosvista = new EstablecimientosVista();

            establecimientosvista = establecimientoservicio.GetAllEstablecimiento();

            return RedirectToAction("Ver", "Instituciones", new { INST_ID = model.Id_Institucion });
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        [HttpPost]
        public ActionResult Modificar_Establecimiento(EstablecimientoVista model)
        {

            model.Id_Institucion = model.Id_Institucion;
            bool mRet = establecimientoservicio.ModificarEstablecimiento(model);

            IEstablecimientosVista establecimientosvista = new EstablecimientosVista();

            establecimientosvista = establecimientoservicio.GetAllEstablecimiento();

            return RedirectToAction("Ver", "Instituciones", new { INST_ID = model.Id_Institucion });

        }

    }
}

tags/version1.0/CbaGob.Alumnos.Web/Views/Establecimientos/Consultar.cshtml
@model  EstablecimientoVista
@{
    ViewBag.Title = "Instituciones";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.Establecimientos.js", Url)
}
<div class="box">
    <h2>
        Consultar Sede</h2>
    <table align="center" style="width: 622px;">
        <tr>
            <td class="style1" style="font-weight: bold">
                <div id="titulo">
                </div>
                @using (Html.BeginForm("Eliminar_Establecimiento", "Establecimientos", FormMethod.Post, new { Id = "FormularioEstablecimiento" }))
                { 
                    @Html.ValidationSummary(true)
                    <br />
                    <table id="myIntituciones" align="center" width="630px">
                        <tr>
                            <td align="left">
                                Nombre Institucion:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.NombreInstitucion, new { disabled = "disabled", style = "width:400px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Nombre Sede:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.NombreEstablecimiento, new { disabled = "disabled", style = "width:350px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Teléfono Sede:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.TelefonoEstablecimiento, new { disabled = "disabled", style = "width:150px;", MaxLength = "64" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Provincia:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Provincia, new { disabled = "disabled", style = "width:250px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Localidad:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Localidad, new { disabled = "disabled", style = "width:250px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Barrio:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Barrio, new { disabled = "disabled", style = "width:250px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Calle:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Calle, new { disabled = "disabled", style = "width:250px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Nro:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Nro, new { disabled = "disabled", style = "width:150px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Representante:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Resposable, new { disabled = "disabled", style = "width:250px;", MaxLength = "50" })
                                @Html.ValidationMessageFor(m => m.Resposable, "*")
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Email Representante:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Emial, new { disabled = "disabled", style = "width:250px;", MaxLength = "50", type = "email" })
                                @Html.ValidationMessageFor(m => m.Emial, "*")
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Teléfono Representante:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Telefono, new { disabled = "disabled", style = "width:150px;", MaxLength = "50" })
                                @Html.ValidationMessageFor(m => m.Telefono, "*")
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Nro Resolución:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Nro_Resolucion, new { disabled = "disabled", style = "width:250px;", MaxLength = "64" })
                                @Html.ValidationMessageFor(m => m.Nro_Resolucion, "*")
                            </td>
                        </tr>
                    </table>
    
                    @Html.HiddenFor(d => d.Id_Establecimiento)
                    @Html.HiddenFor(d => d.Id_Institucion)

                    <table id="myIntituciones" align="center" width="700px">
                        <tr>
                            <td align="right" vlign="middle">
                                @Html.ActionLink("Cancelar", "Ver", "Instituciones", new { INST_ID = Model.Id_Institucion }, new { Class = "btnIngresar" })
                            </td>
                        </tr>
                    </table>
   
                }
            </td>
        </tr>
    </table>
</div>
<div id="dialog" title="Eliminar">
    <p>
        Esta Seguro de Eliminar?</p>
</div>

tags/version1.0/CbaGob.Alumnos.Web/Views/Establecimientos/Eliminar.cshtml
@model  EstablecimientoVista
@{
    ViewBag.Title = "Instituciones";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.Establecimientos.js", Url)
}
<div class="box">
    <h2>
        Eliminar Sede</h2>
    <table align="center" style="width: 622px;">
        <tr>
            <td class="style1" style="font-weight: bold">
                <div id="titulo">
                </div>
                @using (Html.BeginForm("Eliminar_Establecimiento", "Establecimientos", FormMethod.Post, new { Id = "FormularioEstablecimiento" }))
                { 
                    @Html.ValidationSummary(true)
                    <br />
                    <table id="myIntituciones" align="center" width="630px">
                        <tr>
                            <td align="left">
                                Nombre Institucion:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.NombreInstitucion, new { disabled = "disabled", style = "width:400px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Nombre Sede:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.NombreEstablecimiento, new { disabled = "disabled", style = "width:350px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Teléfono Sede:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.TelefonoEstablecimiento, new { disabled = "disabled", style = "width:150px;", MaxLength = "64" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Provincia:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Provincia, new { disabled = "disabled", style = "width:250px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Localidad:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Localidad, new { disabled = "disabled", style = "width:250px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Barrio:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Barrio, new { disabled = "disabled", style = "width:250px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Calle:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Calle, new { disabled = "disabled", style = "width:250px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Nro:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Nro, new { disabled = "disabled", style = "width:150px;", MaxLength = "50" })
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Representante:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Resposable, new { disabled = "disabled", style = "width:250px;", MaxLength = "50" })
                                @Html.ValidationMessageFor(m => m.Resposable, "*")
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Email Representante:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Emial, new { disabled = "disabled", style = "width:250px;", MaxLength = "50", type = "email" })
                                @Html.ValidationMessageFor(m => m.Emial, "*")
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Teléfono Representante:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Telefono, new { disabled = "disabled", style = "width:150px;", MaxLength = "50" })
                                @Html.ValidationMessageFor(m => m.Telefono, "*")
                            </td>
                        </tr>
                        <tr>
                            <td align="left">
                                Nro Resolución:
                            </td>
                            <td align="left" valign="middle">
                                @Html.TextBoxFor(c => c.Nro_Resolucion, new { style = "width:250px;", MaxLength = "64" })
                                @Html.ValidationMessageFor(m => m.Nro_Resolucion, "*")
                            </td>
                        </tr>
                    </table>
    
                    @Html.HiddenFor(d => d.Id_Establecimiento)
                    @Html.HiddenFor(d => d.Id_Institucion)

                    <table id="myIntituciones" align="center" width="700px">
                        <tr>
                            <td align="right" vlign="middle">
                                <input id="Eliminar" type="button" value="Eliminar" class="btnIngresar" />
                                @Html.ActionLink("Cancelar", "Ver", "Instituciones", new { INST_ID = Model.Id_Institucion }, new { Class = "btnIngresar" })
                            </td>
                        </tr>
                    </table>
   
                }
            </td>
        </tr>
    </table>
</div>
<div id="dialog" title="Eliminar">
    <p>
        Esta Seguro de Eliminar?</p>
</div>

tags/version1.0/CbaGob.Alumnos.Web/Views/Establecimientos/Index.cshtml
@model  EstablecimientosVista
@{
    ViewBag.Title = "Instituciones";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Stylesheets {
    @Content.Stylesheet("css/instituciones.css", Url)
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.Establecimientos.js",Url)
}

<div class="box">
  <h2>Listado de Establecimientos</h2>
    <table>
        <tr>
            <td class="style1" style="font-weight: bold">
                <div id="titulo">
                    
                </div>
               @* <div id="titulo">
                    <div id="ttxt">
                        Establecimientos</div>
                     <div id="iconobuscar">
                        @Html.ActionLink("Buscar", "", "",  new { @class = "btngral" })
                    </div>
                    <div id="iconomodificar">
                       @Html.ActionLink("Nuevo", "Agregar", "Establecimientos", null, new { Class = "btngral" })
                    </div>
                </div>*@
                <div id="DivInstituciones">
                    @Html.Partial("_EstablecimientoLista", Model)
                </div>
            </td>
        </tr>
    </table>
</div>

tags/version1.0/CbaGob.Alumnos.Web/Views/Establecimientos/Modificar.cshtml
@model  EstablecimientoVista
@{
    ViewBag.Title = "Instituciones";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.Establecimientos.js", Url)
}
<div class="box">
    <h2>
        Modificar Sede</h2>
    <table align="center" style="width: 622px;">
        <tr>
            <td class="style1" style="font-weight: bold">
                <div id="titulo">
                </div>
                @using (Html.BeginForm("Modificar_Establecimiento", "Establecimientos", FormMethod.Post, new { Id = "FormularioEstablecimiento" }))
                { 
                    @Html.ValidationSummary(true)
                    <br />
                    <table align="center" id="mytable" style="font-family: Arial, Helvetica, sans-serif;
                        font-size: 12px; width: 700px;">
                        <tr>
                            <td>
                                <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 700px;
                                    text-align: center;">
                                    <legend>Datos Sede</legend>
                                     <table align="left" id="mytable" style="font-family: Arial, Helvetica, sans-serif;
                                        font-size: 12px; width: 700px;">
                                        <tr>
                                            <td align="left">
                                                Nombre de la Institución:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.NombreInstitucion, new { style = "width:400px;", MaxLength = "50", disabled = "disabled" })
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                Nombre Sede:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.NombreEstablecimiento, new { style = "width:350px;", MaxLength = "64", placeholder = PlaceHolderConstants.SedeNombre })
                                                @Html.ValidationMessageFor(m => m.NombreEstablecimiento, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                Teléfono Sede:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.TelefonoEstablecimiento, new { style = "width:150px;", MaxLength = "64", placeholder = PlaceHolderConstants.Telefono })
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                Provincia:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Provincia, new { style = "width:250px;", MaxLength = "50", placeholder = PlaceHolderConstants.Provincia })
                                                @Html.ValidationMessageFor(m => m.Provincia, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                Localidad:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Localidad, new { style = "width:250px;", MaxLength = "50", placeholder = PlaceHolderConstants.Localidad })
                                                @Html.ValidationMessageFor(m => m.Localidad, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                Barrio:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Barrio, new { style = "width:250px;", MaxLength = "50", placeholder = PlaceHolderConstants.DireccionBarrio })
                                                @Html.ValidationMessageFor(m => m.Barrio, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                Calle:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Calle, new { style = "width:250px;", MaxLength = "150", placeholder = PlaceHolderConstants.DireccionCalle })
                                                @Html.ValidationMessageFor(m => m.Calle, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                Numero:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Nro, new { style = "width:150px;", MaxLength = "4", placeholder = PlaceHolderConstants.DireccionNumero })
                                                @Html.ValidationMessageFor(m => m.Nro, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                Representante:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Resposable, new { style = "width:250px;", MaxLength = "150", placeholder = PlaceHolderConstants.NombrePersona })
                                                @Html.ValidationMessageFor(m => m.Resposable, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                Email Representante:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Emial, new { style = "width:250px;", MaxLength = "150", type = "email", placeholder = PlaceHolderConstants.Email })
                                                @Html.ValidationMessageFor(m => m.Emial, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                Teléfono Representante:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Telefono, new { style = "width:150px;", MaxLength = "64", placeholder = PlaceHolderConstants.Telefono })
                                                @Html.ValidationMessageFor(m => m.Telefono, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left">
                                                Numero de Resolución:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Nro_Resolucion, new { style = "width:250px;", MaxLength = "64", placeholder = PlaceHolderConstants.Resolucion })
                                                @Html.ValidationMessageFor(m => m.Nro_Resolucion, "*")
                                            </td>
                                        </tr>
                                    </table>
                                </fieldset>
                            </td>
                        </tr>
                    </table>
                    @Html.HiddenFor(d => d.Id_Institucion)
                    @Html.HiddenFor(d => d.Id_Establecimiento)
                    <table id="btnfin" align="center" width="700px">
                        <tr>
                            <td align="right" vlign="middle">
                                <input type="submit" value="Guardar" class="btnIngresar" />&nbsp;&nbsp;
                                @Html.ActionLink("Cancelar", "Ver", "Instituciones", new { INST_ID = Model.Id_Institucion }, new { Class = "btnIngresar" })
                            </td>
                        </tr>
                    </table>
   
                }
            </td>
        </tr>
    </table>
</div>