CbaGob.Alumnos.Web/Controllers/FacturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CbaGob.Alumnos.Modelo.Entities;
using CbaGob.Alumnos.Servicio.Servicios;
using CbaGob.Alumnos.Servicio.ServiciosInterface;
using CbaGob.Alumnos.Servicio.Vistas;
using CbaGob.Alumnos.Servicio.Vistas.Shared;
using CbaGob.Alumnos.Servicio.VistasInterface;
using JLY.Hotel.Web.Controllers;

namespace CbaGob.Alumnos.Web.Controllers
{
    public class FacturaController : BaseController
    {
        private IFacturaServicio FacturaServicio;
        private IInstitucionServicio institucionservicio;
        private ICondicionesCursoServicio condicionescursoservicio;


        public FacturaController(IFacturaServicio facturaServicio, IInstitucionServicio institucionservicio, ICondicionesCursoServicio condicionescursoservicio)
        {
            FacturaServicio = facturaServicio;
            this.institucionservicio = institucionservicio;
            this.condicionescursoservicio = condicionescursoservicio;
        }

        public ActionResult Buscar(DateTime? Fecha, string NroFactura)
        {
            return View("Index", FacturaServicio.GetFacturas(Fecha, NroFactura));
        }

        public ActionResult Index()
        {
            return View("Index", FacturaServicio.GetFacturas(null, ""));
        }

        public ActionResult Agregar(int idCondicionCurso, int IdInstitucion)
        {
            IFacturaVista model = FacturaServicio.GetIndex();

            model.Curso = condicionescursoservicio.GetForModificacion(idCondicionCurso);

            model.Id_Condicion_Curso = idCondicionCurso;

            return View("Agregar", model);
        }

        public ActionResult Detalle(int Idfactura)
        {
            return View("Agregar", FacturaServicio.GetFactura(Idfactura));
        }

        public ActionResult CambiarCondicion(FacturaVista factura)
        {
            return View("Agregar", FacturaServicio.CambiarCondicion(factura));
        }


        public ActionResult Eliminar(int Idfactura)
        {
            IFacturaVista model = new FacturaVista();

            model = FacturaServicio.GetFactura(Idfactura);

            return View(model);
        }

        public ActionResult EliminarFactura(FacturaVista model)
        {
            FacturaServicio.EliminarFactura(model.IdFactura);
            return RedirectToAction("Index");
        }

        public ActionResult GuardarFactura(FacturaVista factura)
        {
            factura.CondicionCurso.Selected = factura.Id_Condicion_Curso.ToString();

            if (ModelState.IsValid)
            {
                if (FacturaServicio.AgregarFactura(factura))
                {
                    return Index();
                }
                AddError(FacturaServicio.GetErrors());
            }
            return CambiarCondicion(factura);
        }

        public ActionResult Seleccion()
        {
            IFacturaVista model = FacturaServicio.GetIndex();

            model.Instituciones = institucionservicio.GetInstituciones();

            return View(model);
        }

        public ActionResult VerCursos(int IdInstitucion)
        {
            IFacturaVista model = new FacturaVista();

            model.Cursos = condicionescursoservicio.GetByInstitucionId(IdInstitucion);

            model.Instituciones = institucionservicio.GetInstituciones();

            return View("Seleccion", model);
        }



        public ActionResult LiquidarFactura()
        {
            return View("Liquidacion", FacturaServicio.GetFacturasbyLiquidacion());
        }


        public ActionResult VerFactura(int Idfactura)
        {
            IFacturaVista model = new FacturaVista();

            model = FacturaServicio.GetFactura(Idfactura);

            return View(model);
        }


        [HttpPost]
        public ActionResult RealizarLiquidacion(FacturaVista model)
        {
            FacturaServicio.LiquidarFactura(model.IdFactura);
            return View("Liquidacion", FacturaServicio.GetFacturasbyLiquidacion());
        }


        public ActionResult IndexPager(Pager pager,DateTime? Fecha,string NroFactura)
        {
            return View("Index", FacturaServicio.GetFacturas(pager, Fecha, NroFactura));
        }


        public ActionResult IndexPagerLiquidacion(Pager pager)
        {
            return View("Liquidacion", FacturaServicio.GetFacturasbyLiquidacion(pager));
        }

    }
}

CbaGob.Alumnos.Web/Views/Factura/Agregar.cshtml
@model FacturaVista
@{
    ViewBag.Title = "Facturaciones";
    ViewBag.SubMenuSelected = "Facturacion";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.Factura.js", Url)
}
<div class="box">
    <h2>
        Agregar Factura</h2>
    <table align="center" style="width: 700px;">
        <tr>
            <td class="style1" style="font-weight: bold">
                <div id="titulo">
                </div>
                @using (Html.BeginForm("GuardarFactura", "Factura", FormMethod.Post, new { id = "FormFactura" }))
                { 
                    @Html.HiddenFor(c => c.Accion)
                    <input type="hidden" name="CambioUrl" id="CambioUrl" value="@Url.Action("CambiarCondicion")" />
                    @Html.ValidationSummary(true)               
                    <table align="center" id="mytable" style="font-family: Arial, Helvetica, sans-serif;
                        font-size: 12px; width: 722px;">
                        <tr>
                            <td>
                                <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 710px;">
                                    <legend>Datos de la Factura</legend>
                                    <table align="center" style="font-family: Arial, Helvetica, sans-serif; font-size: 12px;
                                        width: 710px;">
                                        <tr>
                                            <td align="left" valign="middle">
                                                Nombre Institución:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Curso.NombeInstitucion, new { disabled = "disabled", style = "width:350px;", MaxLength = "50" })
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Catalogo de Especialidades:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Curso.NombreCurso, new { disabled = "disabled", style = "width:350px;", MaxLength = "50" })
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Número de Factura:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.NroFactura, new { style = "width:200px", MaxLength = "50",placeholder = PlaceHolderConstants.FacturaNumero })
                                                @Html.ValidationMessageFor(c => c.NroFactura, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Concepto de Factura:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextAreaFor(c => c.Concepto, new { style = "width:350px;height:45px", MaxLength = "50", placeholder = PlaceHolderConstants.FacturaConcepto })
                                                @Html.ValidationMessageFor(c => c.Concepto, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Descripción:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextAreaFor(c => c.Descripcion, new { style = "width:350px;height:45px", MaxLength = "50", placeholder = PlaceHolderConstants.FacturaDescripcion })
                                                @Html.ValidationMessageFor(c => c.Descripcion, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Item:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextAreaFor(c => c.Item, new { style = "width:350px;height:45px", MaxLength = "50", placeholder = PlaceHolderConstants.FacturaItem })
                                                @Html.ValidationMessageFor(c => c.Item, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Monto:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Monto, new { style = "width:100px;", MaxLength = "8", placeholder = PlaceHolderConstants.FacturaMonto })
                                                @Html.ValidationMessageFor(c => c.Monto, "*")
                                            </td>
                                        </tr>
                                    </table>
                                </fieldset>
                            </td>
                        </tr>
                    </table>
                    @Html.HiddenFor(c => c.Id_Condicion_Curso)
   
                    <table id="myIntituciones" align="center" width="710px">
                        <tr>
                            <td align="right" valign="middle">
                                <input type="submit" value="Guardar" class="btnIngresar" />&nbsp;&nbsp;
                                @Html.ActionLink("Cancelar", "Index", "Factura", null, new { Class = "btnIngresar" })
                            </td>
                        </tr>
                    </table>
                
                }
            </td>
        </tr>
    </table>
</div>

CbaGob.Alumnos.Web/Views/Factura/Eliminar.cshtml
@model FacturaVista
@{
    ViewBag.Title = "Facturaciones";
    ViewBag.SubMenuSelected = "Facturacion";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.Factura.js", Url)
}
<div class="box">
    <h2>
        Eliminar Factura</h2>
    <table align="center" style="width: 700px;">
        <tr>
            <td class="style1" style="font-weight: bold">
                <div id="titulo">
                </div>
                @using (Html.BeginForm("EliminarFactura", "Factura", FormMethod.Post, new { id = "FormFactura" }))
                { 
                    @Html.HiddenFor(c => c.Accion)
                    <input type="hidden" name="CambioUrl" id="CambioUrl" value="@Url.Action("CambiarCondicion")" />
                    @Html.ValidationSummary(true)               
                    <table align="center" id="mytable" style="font-family: Arial, Helvetica, sans-serif;
                        font-size: 12px; width: 722px;">
                        <tr>
                            <td>
                                <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 710px;">
                                    <legend>Datos de la Factura</legend>
                                    <table align="center" style="font-family: Arial, Helvetica, sans-serif; font-size: 12px;
                                        width: 710px;">
                                        <tr>
                                            <td align="left" valign="middle">
                                                Nombre Institución:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.NombreInstitucion, new { disabled = "disabled", style = "width:350px;", MaxLength = "50" })
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Curso Asignado a la Institución:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.NombreCurso, new { disabled = "disabled", style = "width:350px;", MaxLength = "50" })
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Número de Factura:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.NroFactura, new { disabled = "disabled", style = "width:200px", MaxLength = "50" })
                                                @Html.ValidationMessageFor(c => c.NroFactura, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Concepto de Factura:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextAreaFor(c => c.Concepto, new { disabled = "disabled", style = "width:350px;height:45px", MaxLength = "50" })
                                                @Html.ValidationMessageFor(c => c.Concepto, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Descripción:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextAreaFor(c => c.Descripcion, new { disabled = "disabled", style = "width:350px;height:45px", MaxLength = "50" })
                                                @Html.ValidationMessageFor(c => c.Descripcion, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Item:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextAreaFor(c => c.Item, new { disabled = "disabled", style = "width:350px;height:45px", MaxLength = "50" })
                                                @Html.ValidationMessageFor(c => c.Item, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Monto:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Monto, new { disabled = "disabled", style = "width:100px;", MaxLength = "8" })
                                                @Html.ValidationMessageFor(c => c.Monto, "*")
                                            </td>
                                        </tr>
                                    </table>
                                </fieldset>
                            </td>
                        </tr>
                    </table>
                    @Html.HiddenFor(c => c.Id_Condicion_Curso)
                    @Html.HiddenFor(c => c.IdFactura)
   
                    <table id="btnfin" align="center" width="710px">
                        <tr>
                            <td align="right" valign="middle">
                                <input id="Eliminar" type="button" value="Eliminar" class="btnIngresar" />&nbsp;&nbsp;
                                @Html.ActionLink("Cancelar", "Index", "Factura", null, new { Class = "btnIngresar" })
                            </td>
                        </tr>
                    </table>
                
                }
            </td>
        </tr>
    </table>
</div>
<div id="dialog" title="Eliminar">
    <p>
        Está Seguro de Eliminar?</p>
</div>

CbaGob.Alumnos.Web/Views/Factura/Index.cshtml
@model FacturasVista
@{
    ViewBag.Title = "Facturaciones";
    ViewBag.SubMenuSelected = "Facturacion";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.Factura.js", Url)
}
@section Stylesheets {
    @Content.Stylesheet("css/instituciones.css", Url)
}
<div class="box">
    <h2>
        Listado de Facturas</h2>
    @using (Html.BeginForm("IndexPager", "Factura", FormMethod.Post, new { id = "FormIndexFacturas" }))
    {
        @Html.Hidden("UrlBuscar", Url.Action("Buscar"), "UrlBuscar")
        <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 700px;
            margin-left: 5px; margin-top: 5px;">
            <legend style="color: #FF9900">Buscar</legend>
            <table>
                <tr>
                    <td height="35px">
                        Número de Factura:&nbsp;
                    </td>
                    <td>@Html.TextBoxFor(c => c.NroFactura, new { style = "width:100px;", MaxLength = "64", PlaceHolderConstants.FacturaNumero })
                    </td>
                </tr>
                <tr>
                    <td height="35px">
                        Fecha&nbsp;
                    </td>
                    <td>@Html.EditorFor(c => c.Fecha)
                    </td>
                </tr>
                <tr>
                    <td height="35px">
                    </td>
                    <td>
                        <input type="button" id="Buscar" value="Buscar" class="btnIngresar" />
                    </td>
                </tr>
            </table>
        </fieldset>
        <table>
            <tr>
                <td class="style1" style="font-weight: bold">
                    <div id="titulo">
                    </div>
                    <br />
                    <div id="DivInstituciones">
                        @Html.Partial("_FacturaLista", Model)
                    </div>
                </td>
            </tr>
        </table>
        <div style="text-align: left;">
            @Html.Partial("_Pager", Model.Pager)
        </div>
    }
</div>

CbaGob.Alumnos.Web/Views/Factura/VerFactura.cshtml
@model FacturaVista
@{
    ViewBag.Title = "Facturaciones";
    ViewBag.SubMenuSelected = "Facturacion";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.Factura.js", Url)
}
<div class="box">
    <h2>
        Agregar Factura</h2>
    <table align="center" style="width: 700px;">
        <tr>
            <td class="style1" style="font-weight: bold">
                <div id="titulo">
                </div>
                @using (Html.BeginForm("RealizarLiquidacion", "Factura", FormMethod.Post, new { id = "FormFactura" }))
                { 
                    @Html.HiddenFor(c => c.Accion)
                    <input type="hidden" name="CambioUrl" id="CambioUrl" value="@Url.Action("CambiarCondicion")" />
                    @Html.ValidationSummary(true)               
                    <table align="center" id="mytable" style="font-family: Arial, Helvetica, sans-serif;
                        font-size: 12px; width: 722px;">
                        <tr>
                            <td>
                                <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 710px;">
                                    <legend>Datos de la Factura</legend>
                                    <table align="center" style="font-family: Arial, Helvetica, sans-serif; font-size: 12px;
                                        width: 710px;">
                                        <tr>
                                            <td align="left" valign="middle">
                                                Nombre Institución:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.NombreInstitucion, new { disabled = "disabled", style = "width:350px;", MaxLength = "50" })
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Curso Asignado a la Institución:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.NombreCurso, new { disabled = "disabled", style = "width:350px;", MaxLength = "50" })
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Numero de Factura:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.NroFactura, new { disabled = "disabled", style = "width:200px", MaxLength = "50" })
                                                @Html.ValidationMessageFor(c => c.NroFactura, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Concepto de Factura:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextAreaFor(c => c.Concepto, new { disabled = "disabled", style = "width:350px;height:45px", MaxLength = "50" })
                                                @Html.ValidationMessageFor(c => c.Concepto, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Descripción:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextAreaFor(c => c.Descripcion, new { disabled = "disabled", style = "width:350px;height:45px", MaxLength = "50" })
                                                @Html.ValidationMessageFor(c => c.Descripcion, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Item:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextAreaFor(c => c.Item, new { disabled = "disabled", style = "width:350px;height:45px", MaxLength = "50" })
                                                @Html.ValidationMessageFor(c => c.Item, "*")
                                            </td>
                                        </tr>
                                        <tr>
                                            <td align="left" valign="middle">
                                                Monto:
                                            </td>
                                            <td align="left" valign="middle">
                                                @Html.TextBoxFor(c => c.Monto, new { disabled = "disabled", style = "width:100px;", MaxLength = "8" })
                                                @Html.ValidationMessageFor(c => c.Monto, "*")
                                            </td>
                                        </tr>
                                    </table>
                                </fieldset>
                            </td>
                        </tr>
                    </table>
                    @Html.HiddenFor(c => c.Id_Condicion_Curso)
                    @Html.HiddenFor(c => c.IdFactura)
   
                    <table id="btnfin" align="center" width="710px">
                        <tr>
                            <td align="right" valign="middle">
                                <input type="submit" value="Liquidar Factura" class="btnIngresar" />&nbsp;&nbsp;
                                @Html.ActionLink("Cancelar", "LiquidarFactura", "Factura", null, new { Class = "btnIngresar" })
                            </td>
                        </tr>
                    </table>
                
                }
            </td>
        </tr>
    </table>
</div>

CbaGob.Alumnos.Web/Views/Factura/_FacturaLista.cshtml
@model  FacturasVista
@if (Model.Facturas != null && Model.Facturas.Count > 0)
{ 
     <div style="text-align: center;">
        <table id="grilla" align="center" width="722px" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th height="30">
                        <div align="left">
                            Numero de Factura</div>
                    </th>
                    <th height="30">
                        <div align="left">
                            Concepto</div>
                    </th>
                    <th height="30">
                        <div align="left">
                            Fecha</div>
                    </th>
                    <th height="30">
                        <div align="left">
                            Monto Total</div>
                    </th>
                    <th height="30">
                        <div align="right" style="margin-right: 2px;">
                            Acción</div>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Facturas)
                {
                    <tr>
                        <td align="left" height="30">                           
                                @item.NroFactura.ToMaxLenght(30)                           
                          
                        </td>
                        <td align="left">                           
                                @item.Concepto.ToMaxLenght(30)                          
                        </td>
                        <td align="left">                           
                                @item.FechaAlta.ToFecha()                      
                        </td>
                        <td align="left">
                            $@item.MontoTotal
                        </td>
                        <td align="right" style="margin-right: 2px;">
                            @if (ViewBag.SubMenuSelected != "Liquidacion")
                            {
                                @Html.ActionLink("Eliminar", "Eliminar", "Factura", new { Idfactura = item.IdFactura }, new { @class = "btnIngresar" })
                            }
                            else
                            {
                                @Html.ActionLink("Liquidar Factura", "VerFactura", "Factura", new { Idfactura = item.IdFactura }, new { @class = "btnIngresar" })
                            }
                        </td>
                    </tr>
                }
                @if (ViewBag.SubMenuSelected != "Liquidacion")
                {
                    <tr>
                        <td align="right" valign="middle" colspan="5" height="35px">
                            @Html.ActionLink("Agregar Factura", "Seleccion", "Factura", null, new { @class = "btnIngresar" })&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
}
else
{
    <table id="grilla" align="center" width="722px" cellpadding="0" cellspacing="0">
        <tr>
            <td width="722px">
                @Html.Partial("_SinDatos", "Facturas")
            </td>
        </tr>
        @if (ViewBag.SubMenuSelected != "Liquidacion")
        {
            <tr>
                <td align="right" width="722px" height="35px">
                    @Html.ActionLink("Agregar Factura", "Seleccion", "Factura", null, new { @class = "btnIngresar" })
                </td>
            </tr>
        }
    </table>
    
}