tags/version1.0/CbaGob.Alumnos.Web/Controllers/CajaChicaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CbaGob.Alumnos.Servicio.Servicios;
using CbaGob.Alumnos.Servicio.ServiciosInterface;
using CbaGob.Alumnos.Servicio.Vistas;
using CbaGob.Alumnos.Servicio.VistasInterface;

namespace CbaGob.Alumnos.Web.Controllers
{
    [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
    public class CajaChicaController : Controller
    {
        //
        // GET: /CajaChica/
        private ICajaChicaServicio cajachicaservicio;
        private IMovimientoServicio movimientoservicio;


        public CajaChicaController(ICajaChicaServicio cajachicaservicio, IMovimientoServicio movimientoservicio)
        {
            this.cajachicaservicio = cajachicaservicio;
            this.movimientoservicio = movimientoservicio;
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Agregar(int id_institucion)
        {
            ICajaChicaVista model = cajachicaservicio.GetIndex(id_institucion);

            return View(model);
        }

        [HttpPost]
        public ActionResult GuardarCaja(CajaChicaVista model)
        {
            bool mreturn = cajachicaservicio.AgregarCajaChica(model);

            if (mreturn != false)
            { return RedirectToAction("Ver", "Instituciones", new { INST_ID = model.Id_Institucion }); }
            else
            {
                return View("Agregar", model);
            }
        }

        public ActionResult Modificar(int id_institucion, int Id_Caja_Chica)
        {
            ICajaChicaVista model = cajachicaservicio.GetCajaChica(Id_Caja_Chica);

            return View(model);
        }

        public ActionResult ModificarCaja(CajaChicaVista model)
        {
            bool mreturn = cajachicaservicio.ModificaCajaChica(model);

            if (mreturn)
            {
                return RedirectToAction("Ver", "Instituciones", new { INST_ID = model.Id_Institucion });
            }
            else
            {
                ICajaChicaVista vista = cajachicaservicio.GetCajaChica(model.Id_Caja_Chica);
                return View("Modificar", vista);
            }
        }

        public ActionResult Eliminar(int id_institucion, int Id_Caja_Chica)
        {
            ICajaChicaVista model = cajachicaservicio.GetCajaChica(Id_Caja_Chica);

            return View(model);
        }

        public ActionResult EliminarCaja(CajaChicaVista model)
        {
            bool mreturn = cajachicaservicio.EliminarCajaChica(model.Id_Caja_Chica);

            if (mreturn)
            {
                return RedirectToAction("Ver", "Instituciones", new { INST_ID = model.Id_Institucion });
            }
            else
            {
                ICajaChicaVista vista = cajachicaservicio.GetCajaChica(model.Id_Caja_Chica);
                return View("Eliminar", vista);
            }

        }

        public ActionResult Ver(int id_institucion, int Id_Caja_Chica)
        {
            ICajaChicaVista model = cajachicaservicio.GetCajaChica(Id_Caja_Chica);

            model.Moviminetos = movimientoservicio.GetMovimientosByCajaChica(Id_Caja_Chica);

            decimal montototalmovimineto = 0;

            foreach (var movimientos in model.Moviminetos.ListaMoviento)
            {
                montototalmovimineto = montototalmovimineto + movimientos.Monto;
            }

            model.SaldoCaja = model.Monto - montototalmovimineto;

            return View(model);
        }

    }
}

tags/version1.0/CbaGob.Alumnos.Web/Controllers/GruposController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CbaGob.Alumnos.Servicio.Servicios;
using CbaGob.Alumnos.Servicio.ServiciosInterface;
using CbaGob.Alumnos.Servicio.Vistas;
using CbaGob.Alumnos.Servicio.VistasInterface;
using JLY.Hotel.Web.Controllers;

namespace CbaGob.Alumnos.Web.Controllers
{
    public class GruposController : BaseController
    {
        private IGrupoServicio gruposervicio;
        private ICondicionesCursoServicio CondicionesCursoServicio;
        private IHorarioServicio horarioservicio;
        private IAlumnosServicios alumnosservicios;
        private IDocentesServicio docentesservicio;


        public GruposController(IGrupoServicio gruposervicio, ICondicionesCursoServicio condicionesCursoServicio, IHorarioServicio horarioservicio, IAlumnosServicios alumnosservicios, IDocentesServicio docentesservicio)
        {
            this.gruposervicio = gruposervicio;
            CondicionesCursoServicio = condicionesCursoServicio;
            this.horarioservicio = horarioservicio;
            this.alumnosservicios = alumnosservicios;
            this.docentesservicio = docentesservicio;
        }

        public ActionResult Index()
        {

            IGruposVista gruposvista = gruposervicio.GetAllGrupo();

            return View(gruposvista);
        }

        public ActionResult Agregar(int id_condicionCurso)
        {

            IGrupoVista model = new GrupoVista();

            model.Id_Condicion_Curso = id_condicionCurso;

            ICondicionCursoVista condicioncursovista = CondicionesCursoServicio.GetForModificacion(id_condicionCurso);

            model.Id_Institucion = condicioncursovista.IdInstitucion;

            model.Nombre_Curso = condicioncursovista.NombreCurso;

            model.Nombre_Institucion = condicioncursovista.NombeInstitucion;

            model.BuscadorEstablecimientos.Name = "BuscadorEstablecimientos";
            model.BuscadorEstablecimientos.Tipo = "Estableciminetos";
            model.BuscadorEstablecimientos.Relacionado = "Id_Institucion";

            return View(model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        public ActionResult Modificar(int id_grupo)
        {
            IGrupoVista model = new GrupoVista();

            model = gruposervicio.GetGrupo(id_grupo);

            ICondicionCursoVista condicioncursovista = CondicionesCursoServicio.GetForModificacion(model.Id_Condicion_Curso);

            model.Nombre_Curso = condicioncursovista.NombreCurso;

            model.Nombre_Institucion = condicioncursovista.NombeInstitucion;

            model.BuscadorEstablecimientos.Name = "BuscadorEstablecimientos";
            model.BuscadorEstablecimientos.Tipo = "Estableciminetos";
            model.BuscadorEstablecimientos.Relacionado = "Id_Institucion";
            model.BuscadorEstablecimientos.Valor = model.NombreEstablecimiento;

            return View(model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        public ActionResult Eliminar(int id_grupo)
        {
            IGrupoVista model = new GrupoVista();

            model = gruposervicio.GetGrupo(id_grupo);

            model.Nro_Resolucion = "";

            return View(model);
        }

        public ActionResult VerGrupo(int id_grupo)
        {
            IGrupoVista model = new GrupoVista();

            model = gruposervicio.GetGrupo(id_grupo);

            //model.ListaAlumnos = alumnosservicios.GetTodosAlumnosSinGrupo(model.Id_Condicion_Curso).ListaAlumno;

            //model.ListaAlumnosInGrupo = alumnosservicios.GetTodosAlumnosEnGrupo(id_grupo, model.Id_Condicion_Curso).ListaAlumno;

            //model.ListaDocentesNoGrupo = docentesservicio.GetDocentesNotInGrupo(id_grupo).ListaDocentes;

            //model.ListaDocentesInGrupo = docentesservicio.GetDocentesInGrupo(id_grupo).ListaDocentes;

            return View("Ver", model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        public ActionResult AsignarAlumno(int id_grupo, int id_alumno, int id_condicon_curso)
        {
            IGrupoVista model = new GrupoVista();

            bool mret = alumnosservicios.AsiganraGrupo(id_grupo, id_alumno, id_condicon_curso);

            if (mret == false)
            {
                base.AddError(alumnosservicios.GetErrors());
            }

            model = gruposervicio.GetGrupo(id_grupo);

            return View("Ver", model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        public ActionResult DesasignarAlumno(int id_grupo, int id_alumno, int id_condicon_curso)
        {
            IGrupoVista model = new GrupoVista();

            bool mret = alumnosservicios.DesasignaraGrupo(id_grupo, id_alumno, id_condicon_curso);

            model = gruposervicio.GetGrupo(id_grupo);


            //model.ListaAlumnos = alumnosservicios.GetTodosAlumnosSinGrupo(model.Id_Condicion_Curso).ListaAlumno;

            //model.ListaAlumnosInGrupo = alumnosservicios.GetTodosAlumnosEnGrupo(id_grupo, model.Id_Condicion_Curso).ListaAlumno;



            //model.ListaDocentesNoGrupo = docentesservicio.GetDocentesNotInGrupo(id_grupo).ListaDocentes;

            //model.ListaDocentesInGrupo = docentesservicio.GetDocentesInGrupo(id_grupo).ListaDocentes;

            return View("Ver", model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        public ActionResult AsignarDocente(int id_grupo, int id_docente, int id_condicon_curso)
        {
            IGrupoVista model = new GrupoVista();

            bool mret = docentesservicio.AsignarDocentes(id_docente, id_grupo, id_condicon_curso);

            if (mret == false)
            {
                base.AddError(docentesservicio.GetErrors());
            }

            model = gruposervicio.GetGrupo(id_grupo);

            //model.ListaAlumnos = alumnosservicios.GetTodosAlumnosSinGrupo(model.Id_Condicion_Curso).ListaAlumno;

            //model.ListaAlumnosInGrupo = alumnosservicios.GetTodosAlumnosEnGrupo(id_grupo, model.Id_Condicion_Curso).ListaAlumno;

            //model.ListaDocentesNoGrupo = docentesservicio.GetDocentesNotInGrupo(id_grupo).ListaDocentes;

            //model.ListaDocentesInGrupo = docentesservicio.GetDocentesInGrupo(id_grupo).ListaDocentes;

            return View("Ver", model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        public ActionResult DesasignarDocente(int id_grupo, int id_docente, int id_condicon_curso)
        {
            IGrupoVista model = new GrupoVista();

            bool mret = docentesservicio.DesasignarDocentes(id_docente, id_grupo, id_condicon_curso);

            model = gruposervicio.GetGrupo(id_grupo);


            //model.ListaAlumnos = alumnosservicios.GetTodosAlumnosSinGrupo(model.Id_Condicion_Curso).ListaAlumno;

            //model.ListaAlumnosInGrupo = alumnosservicios.GetTodosAlumnosEnGrupo(id_grupo, model.Id_Condicion_Curso).ListaAlumno;


            //model.ListaDocentesNoGrupo = docentesservicio.GetDocentesNotInGrupo(id_grupo).ListaDocentes;

            //model.ListaDocentesInGrupo = docentesservicio.GetDocentesInGrupo(id_grupo).ListaDocentes;

            return View("Ver", model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        public ActionResult AgregarHorario(int id_grupo, int id_horario)
        {
            IGrupoVista model = new GrupoVista();

            horarioservicio.AgregarHorarioAGrupo(id_grupo, id_horario);

            model = gruposervicio.GetGrupo(id_grupo);

            model.ListaAlumnos = alumnosservicios.GetTodosAlumnosSinGrupo(model.Id_Condicion_Curso).ListaAlumno;

            model.ListaAlumnosInGrupo = alumnosservicios.GetTodosAlumnosEnGrupo(id_grupo, model.Id_Condicion_Curso).ListaAlumno;

            model.ListaDocentesNoGrupo = docentesservicio.GetDocentesNotInGrupo(id_grupo).ListaDocentes;

            model.ListaDocentesInGrupo = docentesservicio.GetDocentesInGrupo(id_grupo).ListaDocentes;

            return View("Ver", model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        public ActionResult SacarHorario(int id_grupo, int id_horario)
        {
            IGrupoVista model = new GrupoVista();


            horarioservicio.SacarHorarioAGrupo(id_grupo, id_horario);

            model = gruposervicio.GetGrupo(id_grupo);


            model.ListaAlumnos = alumnosservicios.GetTodosAlumnosSinGrupo(model.Id_Condicion_Curso).ListaAlumno;

            model.ListaAlumnosInGrupo = alumnosservicios.GetTodosAlumnosEnGrupo(id_grupo, model.Id_Condicion_Curso).ListaAlumno;


            model.ListaDocentesNoGrupo = docentesservicio.GetDocentesNotInGrupo(id_grupo).ListaDocentes;

            model.ListaDocentesInGrupo = docentesservicio.GetDocentesInGrupo(id_grupo).ListaDocentes;

            return View("Ver", model);
        }

        [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
        [HttpPost]
        public ActionResult Agregar_Grupo(GrupoVista model)
        {

            model.Id_Condicion_Curso = model.Id_Condicion_Curso;
            bool mRet = gruposervicio.AgregarGrupo(model);

            return RedirectToAction("VerCondicionCurso", "CondicionesCurso", new { idCondicionCurso = model.Id_Condicion_Curso, IdInstitucion = model.Id_Institucion });
        }


tags/version1.0/CbaGob.Alumnos.Web/Controllers/MovimientoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CbaGob.Alumnos.Servicio.Servicios;
using CbaGob.Alumnos.Servicio.ServiciosInterface;
using CbaGob.Alumnos.Servicio.Vistas;
using CbaGob.Alumnos.Servicio.VistasInterface;

namespace CbaGob.Alumnos.Web.Controllers
{
    [ViewAuthorize(Rol = new RolTipo[] { RolTipo.Supervisor, RolTipo.ResponsableIFP })]
    public class MovimientoController : Controller
    {
        //
        // GET: /Movimiento/

        private IMovimientoServicio moviminetoservicio;


        public MovimientoController(IMovimientoServicio moviminetoservicio)
        {
            this.moviminetoservicio = moviminetoservicio;
        }

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Agregar(int id_institucion, int Id_Caja_Chica)
        {
            IMovimientoVista model = moviminetoservicio.GetIndex();

            model.Id_Caja_Chica = Id_Caja_Chica;

            model.Id_Institucion = id_institucion;


            return View(model);
        }

        [HttpPost]
        public ActionResult GuardarMovimineto(MovimientoVista model)
        {

            bool mret = moviminetoservicio.AgregarMovimiento(model);

            return RedirectToAction("Ver", "Instituciones", new { INST_ID = model.Id_Institucion });
        }

        public ActionResult Modificar(int Id_Movimineto)
        {
            IMovimientoVista model = moviminetoservicio.GetMovimiento(Id_Movimineto);

            return View(model);
        }

        [HttpPost]
        public ActionResult ModificarMovimineto(MovimientoVista model)
        {

            bool mret = moviminetoservicio.ModificarMovimiento(model);

            return RedirectToAction("Ver", "Instituciones", new { INST_ID = model.Id_Institucion });
        }

        public ActionResult Eliminar(int Id_Movimineto)
        {
            IMovimientoVista model = moviminetoservicio.GetMovimiento(Id_Movimineto);

            model.TipoMovimiento.Enabled = false;

            return View(model);
        }

        [HttpPost]
        public ActionResult EliminarMovimineto(MovimientoVista model)
        {

            bool mret = moviminetoservicio.EliminarMovimiento(model.Id_Movimiento);

            return RedirectToAction("Ver", "Instituciones", new { INST_ID = model.Id_Institucion });
        }

    }
}

tags/version1.0/CbaGob.Alumnos.Web/Views/CajaChica/Eliminar.cshtml
@model CajaChicaVista
@{
    ViewBag.Title = "Instituciones";
    ViewBag.SubMenuSelected = "Instituciones";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.CajaChica.js", Url)
}
<div class="box">
    <h2>
        Eliminar Caja a Institucion</h2>
    <table align="center" style="width: 700px;">
        <tr>
            <td class="style1" style="font-weight: bold">
                <div id="titulo">
                </div>
                @using (Html.BeginForm("EliminarCaja", "CajaChica", FormMethod.Post, new { Id = "FormularioCajaChica" }))
                { 
                   
                    @Html.HiddenFor(c => c.Id_Caja_Chica)
                    @Html.HiddenFor(c => c.Id_Institucion)
                    @Html.ValidationSummary(true)
                    <br />
                    <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 700px;">
                        <legend style="color: #FF9900">Datos de la Caja</legend>
                        <table align="left" style="font-family: Arial, Helvetica, sans-serif; font-size: 12px;
                            width: 700px;">
                            <tr>
                                <td>
                                    Nombre de la Institución:
                                </td>
                                <td>
                                    @Html.TextBoxFor(c => c.NombreInstitucion, new { style = "width:350px;", MaxLength = "50", disabled = "disabled" })
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Estado de la Caja:
                                </td>
                                <td>
                                    @Html.TextBoxFor(c => c.NombreEstadoCaja, new { style = "width:350px;", MaxLength = "50", disabled = "disabled" })
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    @Html.LabelFor(c=> c.Monto)
                                </td>
                                <td>
                                    @Html.TextBoxFor(c => c.Monto, new { style = "width:150px;", MaxLength = "50", disabled = "disabled" })
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                    <table id="myIntituciones" align="center" width="700px">
                        <tr>
                            <td align="right" valign="middle">
                                <input id="Eliminar" type="button" value="Eliminar" class="btnIngresar" />&nbsp;&nbsp;
                                @Html.ActionLink("Cancelar", "Ver", "Instituciones", new { INST_ID = Model.Id_Institucion }, new { Class = "btnIngresar" })
                            </td>
                        </tr>
                    </table>
                }
            </td>
        </tr>
    </table>
</div>
<div id="dialog" title="Eliminar">
    <p>
        Esta Seguro de Eliminar?</p>
</div>

tags/version1.0/CbaGob.Alumnos.Web/Views/CajaChica/Index.cshtml
@model  CajaChicasVista
@{
    ViewBag.Title = "CajaChica";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Stylesheets {
    @Content.Stylesheet("css/instituciones.css", Url)
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.CajaChica.js", Url)
}
<div class="box">
    <h2>
        Listado de Caja Chica</h2>
    <table>
        <tr>
            <td class="style1" style="font-weight: bold">
                <div id="titulo">
                    <div id="DivInstituciones">
                        @Html.Partial("_CajaChicaLista", Model)
                    </div>
            </td>
        </tr>
    </table>
</div>

tags/version1.0/CbaGob.Alumnos.Web/Views/CajaChica/Modificar.cshtml
@model CajaChicaVista
@{
    ViewBag.Title = "Instituciones";
    ViewBag.SubMenuSelected = "Instituciones";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.CajaChica.js", Url)
}
<div class="box">
    <h2>
        Modificar Caja a Institucion</h2>
    <table align="center" style="width: 700px;">
        <tr>
            <td class="style1" style="font-weight: bold">
                <div id="titulo">
                </div>
                @using (Html.BeginForm("ModificarCaja", "CajaChica", FormMethod.Post, new { Id = "FormularioCajaChica" }))
                { 
                   
                    @Html.HiddenFor(c => c.Id_Caja_Chica)
                    @Html.HiddenFor(c => c.Id_Institucion)
                    @Html.ValidationSummary(true)
                    <br />
                    <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 700px;">
                        <legend style="color: #FF9900">Datos de la Caja</legend>
                        <table align="left" style="font-family: Arial, Helvetica, sans-serif; font-size: 12px;
                            width: 700px;">
                            <tr>
                                <td>
                                    Nombre de la Institución:
                                </td>
                                <td>
                                    @Html.TextBoxFor(c => c.NombreInstitucion, new { style = "width:350px;", MaxLength = "50", disabled = "disabled" })
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Estado de la Caja:
                                </td>
                                <td>
                                    @Html.EditorFor(c => c.EstadoCaja)
                                </td>
                            </tr>
                            <tr>
                                <td>
                                   @Html.LabelFor(c => c.Monto)
                                </td>
                                <td>
                                    @Html.TextBoxFor(c => c.Monto, new { style = "width:150px;", MaxLength = "50" })
                                    @Html.ValidationMessageFor(c=> c.Monto,"*")
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                    <table id="btnfin" align="center" width="700px">
                        <tr>
                            <td align="right" valign="middle">
                                <input type="submit" value="Guardar" class="btnIngresar" />
                                @Html.ActionLink("Cancelar", "Ver", "Instituciones", new { INST_ID = Model.Id_Institucion }, new { Class = "btnIngresar" })
                            </td>
                        </tr>
                    </table>
                }
            </td>
        </tr>
    </table>
</div>

tags/version1.0/CbaGob.Alumnos.Web/Views/CajaChica/Ver.cshtml
@model CajaChicaVista
@{
    ViewBag.Title = "Instituciones";
    ViewBag.SubMenuSelected = "Instituciones";
    Layout = "~/Views/Shared/_MasterSGC.cshtml";
}
@section Scripts{
    @Content.Script("CbaGob.Alumnos.Movimientos.js", Url)
}
<div class="box">
    <h2>
        Movimientos Caja Chica</h2>
    <table align="center" style="width: 700px;">
        <tr>
            <td class="style1" style="font-weight: bold">
                <div id="titulo">
                </div>
                @using (Html.BeginForm("Eliminar_Grupo", "Grupos", FormMethod.Post, new { Id = "FormularioGrupos" }))
                { 
                    <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 700px;">
                        <legend style="color: #FF9900">Datos de la Caja</legend>
                        <table>
                            <tr>
                                <td>
                                    Nombre Institución:
                                </td>
                                <td>
                                    @Html.TextBoxFor(c => c.NombreInstitucion, new { disabled = "disabled", style = "width:200px;", MaxLength = "50", Class = "asd" })
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Estado Caja Chica:
                                </td>
                                <td>
                                    @Html.TextBoxFor(c => c.NombreEstadoCaja, new { disabled = "disabled", style = "width:150px;", MaxLength = "50", Class = "asd" })
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Saldo Caja:
                                </td>
                                <td>
                                    @Html.TextBoxFor(c => c.SaldoCaja, new { disabled = "disabled", style = "width:150px;", MaxLength = "50", Class = "asd" })
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                    <fieldset style="font-family: Arial, Helvetica, sans-serif; font-size: 12px; width: 700px;">
                        <legend style="color: #FF9900">Movimientos </legend>
                        <table>
                            <tr>
                                <td>@Html.Partial("_MovimientosLista", Model)
                                </td>
                            </tr>
                        </table>
                    </fieldset>
                  
                    <table style="width: 700px;" id="btnfin">
                        <tr>
                            <td align="right">
                                @Html.ActionLink("Volver al Listado de Instituciones", "Index", "Instituciones", null, new { @class = "btnIngresar" })
                                 @Html.ActionLink("Volver", "Ver", "Instituciones", new { INST_ID = Model.Id_Institucion }, new { @class = "btnIngresar" })
                            </td>
                        </tr>
                    </table>
                    
    
                }
            </td>
        </tr>
    </table>
</div>

tags/version1.0/CbaGob.Alumnos.Web/Views/CajaChica/_MovimientosLista.cshtml
@model CajaChicaVista
@if (Model.Moviminetos.ListaMoviento != null && Model.Moviminetos.ListaMoviento.Count > 0)
{ 
    <div id="tab" style="text-align: center;">
        <table class="TablaPersonal" align="center" width="690px" cellpadding="0" cellspacing="0">
            <thead>
                <tr>
                    <th height="30">
                        <div align="center">
                            Nombre Movimiento</div>
                    </th>
                    <th height="30">
                        <div align="center">
                            Fecha</div>
                    </th>
                    <th height="30">
                        <div align="center">
                            Monto</div>
                    </th>
                    <th height="30">
                        <div align="right" style="margin-right: 2px;">
                            Acción</div>
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Moviminetos.ListaMoviento)
                {
                    <tr>
                        <td align="center" height="28">
                            @item.Nombre_Movimiento
                        </td>
                        <td align="center">
                            @item.Fecha.ToShortDateString()
                        </td>
                        <td align="right">
                            @item.Monto.ToString("C") 
                        </td>
                        <td align="right" style="margin-right: 2px;">
                            @Html.ActionLink("Modificar", "Modificar", "Movimiento", new { id_institucion = Model.Id_Institucion, Id_Movimineto = item.Id_Movimiento }, new { @class = "btnIngresar" })
                            @Html.ActionLink("Eliminar", "Eliminar", "Movimiento", new { id_institucion = Model.Id_Institucion, Id_Movimineto = item.Id_Movimiento }, new { @class = "btnIngresar" })
                        </td>
                    </tr>
                }
                <tr>
                    <td align="left" valign="middle" colspan="2" height="20">
                        <div id="resumenPag" style="height: 20px; padding: 10px 5px 0 2px;">                           
                        </div>
                    </td>
                    <td align="right" valign="bottom" colspan="2" height="20">
                        <div style="height: 20px; padding: 15px 5px 0 2px;">
                            @Html.ActionLink("Agregar Movimiento", "Agregar", "Movimiento", new { id_institucion = Model.Id_Institucion, Id_Caja_Chica = Model.Id_Caja_Chica }, new { @class = "btnIngresar" })
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
}
else
{
    <table id="grilla" align="center" width="690px" cellpadding="0" cellspacing="0">
        <tr>
            <td width="722px">
                @Html.Partial("_SinDatos", "Movimiento")
            </td>
        </tr>
        <tr>
            <td align="right" width="722px" height="35px">
                @Html.ActionLink("Agregar Movimiento", "Agregar", "Movimiento", new { id_institucion = Model.Id_Institucion, Id_Caja_Chica = Model.Id_Caja_Chica }, new { @class = "btnIngresar" })
            </td>
    </table>
}